create multi environments workflow

diff --git a/.github/workflows/terraform_deploy.yml b/.github/workflows/terraform_deploy.yml
--- a/.github/workflows/terraform_deploy.yml
+++ b/.github/workflows/terraform_deploy.yml
@@ -35,7 +35,7 @@ jobs:
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ${{ secrets.AWS_REGION }}
+        aws-region: ${{ vars.AWS_REGION }}
 
     - name: Checkout
       uses: actions/checkout@v4
@@ -43,14 +43,33 @@ jobs:
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
 
+    - name: Select backend configuration
+      run: |
+        echo "Selecting backend configuration for environment: ${{ github.event.inputs.environment }}"
+        BACKEND_FILE="/home/runner/work/devrate-web/devrate-web/${{ env.working-directory }}/${{ github.event.inputs.environment }}.backend"
+        if [[ ! -f "$BACKEND_FILE" ]]; then
+          echo "Error: Backend file $BACKEND_FILE does not exist."
+          exit 1
+        fi
+        echo "Using backend configuration: $BACKEND_FILE"
+
+    - name: Select .tfvars file based on environment
+      run: |
+        echo "Selecting .tfvars file for environment: ${{ github.event.inputs.environment }}"
+        if [[ ! -f "/home/runner/work/devrate-web/devrate-web/${{ env.working-directory }}/${{ github.event.inputs.environment }}.tfvars" ]]; then
+          echo "Error: File ${{ github.event.inputs.environment }}.tfvars does not exist in /home/runner/work/devrate-web/devrate-web/${{ env.working-directory }}."
+          exit 1
+        fi
+
     - name: Terraform Init
-      run: terraform init -upgrade
+      run: |
+        terraform init -backend-config="/home/runner/work/devrate-web/devrate-web/${{ env.working-directory }}/${{ github.event.inputs.environment }}.backend" -reconfigure
 
     - name: Terraform Format
       run: terraform fmt -check
 
     - name: Terraform Plan
-      run: terraform plan -input=false
+      run: terraform plan -input=false -var-file=${{ github.event.inputs.environment }}.tfvars
 
-    - name: Terraform apply
-      run: terraform apply -auto-approve -input=false
+    - name: Terraform Apply
+      run: terraform apply -auto-approve -input=false -var-file=${{ github.event.inputs.environment }}.tfvars
